version: '3.8'

volumes:
  docker-postgres:
  app:
networks:
  postgres:
    name: rest-serivce
    driver: bridge

services:
  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
      context: .
    command: npm run start:dev
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app/
      - /app/node_modules
    environment:
      - PORT=${PORT}
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    command: postgres -c logging_collector=on
    volumes:
      - docker-postgres:${PGDATA}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA:${PGDATA}
